In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 4.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 4.6 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np

# Creating a 1D array
arr1 = np.array ([1, 2, 3, 4, 5])
print (arr1)
print (type(arr1))
print (arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array ([1, 2, 3, 4, 5])
arr2.reshape (5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
arr3 = np.array ([[1, 2, 3], [4, 5, 6]])
print (arr3)
print (arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
np.arange (0, 10, 2).reshape (5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones ((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arrEg = np.array ([[1, 2, 3], [4, 5, 6]])

print ("Array:\n", arrEg)
print ("Shape:", arrEg.shape)
print ("Number of dimensions:", arrEg.ndim)
print ("Size (number of elements):", arrEg.size)
print ("Item Size (in bytes):", arrEg.itemsize)
print ("Data Type:", arrEg.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Item Size (in bytes): 8
Data Type: int64


In [7]:
arrx = np.array ([1, 2, 3, 4, 5])
arry = np.array ([10, 20, 30, 40, 50])

print ("Addition:", arrx + arry)
print ("Subtraction:", arry - arrx)
print ("Multiplication:", arrx * arry)
print ("Division:", arry / arrx)
print ("Exponentiation:", arrx ** 2)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Exponentiation: [ 1  4  9 16 25]


In [2]:
import numpy as np
## Universal functions
arr = np.array ([2, 3, 4, 5, 6])
## square root
print (np.sqrt (arr))
## exponential
print (np.exp (arr))
## sin
print (np.sin (arr))
## natural logarithm
print (np.log (arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [5]:
## Array slicing and indexing

import numpy as np
arr = np.array ([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print (arr[0, 0])
print (arr[2:])
print (arr[0:2, 2:])


1
[[ 9 10 11 12]]
[[3 4]
 [7 8]]


In [ ]:
arr[0, 0] = 100
# print (arr)
arr[1:] = 200
print (arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [200 200 200 200]
 [200 200 200 200]]


In [18]:
## Statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array ([1, 2, 3, 4, 5])

# calculate the mean and standard deviation
mean = np.mean (data)
std_dev = np.std (data)

# normalize the data
normalized_data = (data - mean) / std_dev
print ("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
data = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean (data)
print ("Mean:", mean)

median = np.median (data)
print ("Median:", median)

std_dev = np.std (data)
print ("Standard Deviation:", std_dev)

variance = np.var (data)
print ("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical operation

data = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[(data >= 5) & (data <= 8)]

array([6, 7, 8])